# Concurrency In Go

## 第5章 大规模并发

### 异常传递

在并发代码中,特别是在分布式系统中编写并发代码,很容易出现错误,而且不容易理解错误发生的原因.通过仔细思考问题是如何在系统中传播的,以及问题最终是如何呈现给用户的,你可以避免你自己、你的团队和你的用户遭受很多痛苦.在[错误处理](https://github.com/rayallen20/ConcurrencyInGo/blob/master/note/%E7%AC%AC4%E7%AB%A0%20GO%E8%AF%AD%E8%A8%80%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B%E8%8C%83%E5%BC%8F/5.%20%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86.md)部分,我们讨论了如何在goroutine间传递错误,但是我们并没有讨论错误应该是什么样的,也没有讨论错误如何贯穿一个庞大而复杂的系统.让我们花点时间来讨论错误传递的哲学.以下观点是一个在并发系统中错误处理方面的武断准则.

许多开发者错误地认为异常传播是他们系统中次要的部分,甚至是"其他"部分.他们会仔细思考数据在系统中是如何流动的,但错误则被他们认为是可以容忍的,错误不加思考的向调用栈上层传递,最终直接呈现给用户.GO通过强制开发者在调用栈的每个层级处理错误的方式来纠正这种不良实践.但错误仍然被认为是系统控制流中的二等公民.稍加思考就可以让错误处理成为你系统中的重要资产,并为你的用户带来愉悦的体验.

首先让我们来探讨一下:错误是什么?错误何时发生?错误可以为我们提供什么?

错误表示系统进入了一种状态,在这种状态下,系统无法完成用户明确的或隐含的请求操作.因此,他需要传递一些关键信息:

##### 发生了什么

这是错误的一部分,其中包含有关发生事件的信息.例如:"磁盘已满"、"套接字关闭"或"凭证过期".这些信息很可能是由生成错误的实体隐式生成的,你可以用一些能够帮助到用户的上下文信息来完善这部分信息

##### 何时何处发生

错误始终应该包含一个完整的堆栈跟踪信息,从调用链的发起处开始,直到错误被实例化的位置为止.堆栈跟踪信息不应该包含在错误信息中(稍后详细说明),但是在处理错误时,应该能够轻松获取到堆栈跟踪信息.

此外,错误应该包含有关它运行环境相关的上下文.例如在一个分布式系统中,错误应该有一种方式来标识发生错误的机器.之后,当试图了解系统中发生的情况时,这些信息将具有无法估量的价值

此外,错误应该包含它被实例化时的机器时钟,以UTC表示

##### 有效的信息说明

显示给用户的错误信息应该根据你的系统和系统的用户进行定制.错误信息应该仅包含关于"发生了什么"和"何时何处发生"的简短且相关的信息.友好的消息是以人为中心的,给出一些信息说明这些问题是否是暂时的,并且应该是长度在一行以内的文本即可.

##### 告知用户如何获取更多信息

在某些情况下,有人可能想要知道当错误发生时的详细情况.向用户呈现的错误应该提供一个ID,根据这个ID可以查询到错误对应的详细日志.这个日志中记录了错误发生的时间(不是错误记录的时间)、错误发生时完整的堆栈调用(包括你自己放入错误中的信息).在堆栈跟踪信息中包含一个哈希值也有助于在错误跟踪器中聚合类似的异常.

默认状态下,如果你不介入,异常不会包含上述所有的信息.因此你可以认为:任何展现给用户的异常,如果没有包含上述信息,那么就是一种错误甚至可以被认为是bug.这引出了一个可用来处理异常的通用模型.所有的异常几乎都能归为以下两种分类之一:

- Bug
- 已知的边缘情况(例如:网络连接断开、磁盘写入失败等)

Bug是一些你没有在系统中定义的异常,或者所谓的"原生"异常(即:你是知道触发Bug的边缘情况的).有时候Bug是有意为之的,在你系统最初的几次迭代中将一些异常展示给用户是可接受的.有时候这种情况是无意的.但如果你同意上述提出的方法,那么"原生"异常总是Bug.在确认如何传播错误、在系统随着时间推移如何增长以及最终向用户展示什么内容这几个方面,这种区别将非常有用.

想象一个多模块的大型系统:

![多模块的大型系统](../../img/chapter5/多模块的大型系统.jpg)

假设在底层组件中触发了一个异常,并且这个异常是良构的.这个异常会被传递给上层调用栈.在底层组件的上下文中,这个异常可能是良构的,但是放在整个系统的上下文中,可能并非如此.例如:如果我们在中层组件中调用底层组件中一个可能会出错的函数时,可以这样写:

```go
func PostReport(id string) error {
	result, err := lowlevel.DoWork()
	if err != nil {
		if _, ok := err.(lowlevel.Error); ok {
			err = WrapErr(err, "cannot post report with id %q", id)
		}
		// ...
	}
}
```

- 第4行:`if _, ok := err.(lowlevel.Error); ok`.此处检查接收到的异常,确保接收到的是一个良构的异常.如果不是,就简单地将异常传递到调用栈上,以表明这里发生的错误是个bug
- 第5行:`err = WrapErr(err, "cannot post report with id %q", id)`.此处我们使用一个假设的函数将传入的异常和模块相关的信息封装起来,并赋予这个异常一个新的类型.需要注意的是,封装异常可能会隐藏一些底层的细节,这些细节对于用户来说可能并不重要

在异常最初被实例化时,异常信息中会记录一些底层信息(例如异常发生在哪个goroutine、异常发生在哪台机器、异常的堆栈跟踪等).但是我们的架构规定:我们应该在模块与模块的边界处将底层异常转换为当前模块的错误类型,这个类型转换的过程有可能会将底层信息改写成与当前模块相关的信息.现在,任何不在模块范围内定义的错误类型都可以被视为是非正确格式的异常或者Bug.注意,只有在自己的模块边界(公共函数/方法)或当你的代码可以向异常中添加有价值的上下文这两种情况下,才需要以这种形式封装异常.通常这种做法可以防止在大量的代码中重新封装异常信息.

这种机制可以使我们的系统能够有机地发展.我们可以确保传入的异常是良构的.反过来说,我们可以确保考虑到了异常如何离开我们的模块.异常的正确性也成为了我们系统中的一个关键属性.我们从一开始就尽可能明确地处理不规范的异常,并且随着时间的推移,我们也在逐步形成我们自己对于异常的处理和纠正方面的规范.通过清晰地描述异常类型的方式,我们很明确地划分出何种异常将最终会展示给用户.

如上文描述,所有的异常都应该被记录下来并提供尽可能多的信息.但是在向用户显示错误时,bug和已知的边缘情况还是有一定的区别的.

当面向用户部分的代码收到一个良构的异常时,我们可以确信在代码的所有层级中,都精心设计了错误信息,到了面向用户部分的代码中只需要简单的记录日志并将其打印出来给用户看就可以了.确信的逻辑基点在于:异常被定义了正确的类型.

当一个不规范的异常或bug传播给用户时,我们也应该将异常记录下来,然后应该显示一条用户友好的信息,说明发生了意外情况.如果我们的系统中支持自动异常报告,那么这个异常应该作为一个bug被提交.如果我们的系统不支持这种方式,那么应该建议用户提交一个bug报告.注意,非良构的异常可能包含有用的信息,但我们无法保证这一点.我们唯一能确认的是这个异常没有被我们自定义类型.因此我们应该直接向用户展示一段人类可读的信息,用于解释刚刚发生了什么.

记住,无论是良构的异常还是不规范的异常,我们都应该在异常信息中包含一个日志ID,以便在用户需要更多信息时可以参考.因此,如果bug中包含了有用的信息,那么有需要的用户仍然可以进一步追踪.

我们来看一个完整的例子.这个例子并不是非常健壮(例如,错误类型可能过于简单;调用栈是线性的导致需要在模块边界封装异常这件事不明显).同时,在书中很难表示不同包中的函数,因此我们将进行一些假设.

首先,我们来创建一个异常类型,它包含了一个格式良好的异常应有的内容:

`ConcurrencyInGo/code/chapter5/02-propagationError/customError/myError.go`:

```go
package customError

import (
	"fmt"
	"runtime/debug"
)

type MyError struct {
	Inner      error // 用于存储要封装的异常
	Message    string
	StackTrace string                 // 用于记录当异常发生时的堆栈跟踪信息
	Misc       map[string]interface{} // 用于存储其他杂项信息
}

func WrapError(err error, formatMsg string, msgArgs ...interface{}) MyError {
	return MyError{
		Inner:      err,
		Message:    fmt.Sprintf(formatMsg, msgArgs...),
		StackTrace: string(debug.Stack()),
		Misc:       make(map[string]interface{}),
	}
}

func (e MyError) Error() string {
	return e.Message
}
```

- 第17行:`Inner: err`.该字段用于存储要封装的异常.当我们需要调查发生了什么时,我们总是希望能够查看到最底层的异常信息.
- 第19行:`StackTrace: string(debug.Stack())`.该字段用于记录当异常发生时的堆栈跟踪信息.一个更复杂的异常类型则会省略`wrapError()`栈帧
- 第20行:`Misc: make(map[string]interface{})`.该字段用于存储其他杂项信息.可以将并发ID、对战追踪的哈希值或其他有助于诊断异常的上下文信息存储在该字段中.

接下来创建`lowLevel`模块:

`ConcurrencyInGo/code/chapter5/02-propagationError/lowLevel/lowLevel.go`:

```go
package lowLevel

import (
	"code/chapter5/02-propagationError/customError"
	"os"
)

type LowLevelErr struct {
	error
}

func IsGloballyExec(path string) (bool, error) {
	info, err := os.Stat(path)
	if err != nil {
		return false, LowLevelErr{error: customError.WrapError(err, err.Error())}
	}

	return info.Mode().Perm()&0100 == 0100, nil
}
```

- 第15行:`return false, LowLevelErr{error: customError.WrapError(err, err.Error())}`.此处使用自定义异常类型`LowLevelErr`来封装调用`os.Stat()`后的原始异常.由于我们不希望隐藏这个原始错误的信息,因此我们也不会修改它

接下来创建`intermediate`模块,该模块会调用`lowLevel`模块所在的包:

`ConcurrencyInGo/code/chapter5/02-propagationError/intermediate/intermediate.go`:

```go
package intermediate

import (
	"code/chapter5/02-propagationError/customError"
	"code/chapter5/02-propagationError/lowLevel"
	"os/exec"
)

type IntermediateErr struct {
	error
}

func RunJob(id string) error {
	const jobBinPath = "/bad/job/path"
	isExecutable, err := lowLevel.IsGloballyExec(jobBinPath)

	if err != nil {
		return err // 来自lowLevel包的错误
	} else if isExecutable == false {
		return customError.WrapError(nil, "job binary is not executable") // 本包的错误
	}

	return exec.Command(jobBinPath, "--id="+id).Run()
}
```

- 第18行`return err`.此处直接将来自`lowLevel`模块的异常透传给了调用者
- 第23行`return exec.Command(jobBinPath, "--id="+id).Run()`.此处没有在本模块内封装这个异常
- 按照我们上述的决策,这两种情况均没有在本模块内封装自定义类型的异常,因此都可以被视为bug.这将会给后续的调用带来问题

最后,创建一个调用`intermediate`包的顶级`main()`函数:

`ConcurrencyInGo/code/chapter5/02-propagationError/main.go`:

```go
package main

import (
	"code/chapter5/02-propagationError/intermediate"
	"fmt"
	"log"
	"os"
)

func main() {
	log.SetOutput(os.Stdout)
	log.SetFlags(log.Ltime | log.LUTC)
	err := intermediate.RunJob("1")
	if err != nil {
		msg := "There was an unexpected issue; please report this as a bug."
		if _, ok := err.(intermediate.IntermediateErr); ok {
			msg = err.Error()
		}

		handlerError(1, err, msg)
	}
}

func handlerError(key int, err error, message string) {
	log.SetPrefix(fmt.Sprintf("[logID: %v] ", key))
	log.Printf("%#v", err)
	fmt.Printf("[%v] %v\n", key, message)
}
```

- 第16行:`if _, ok := err.(intermediate.IntermediateErr); ok`.此处检查异常是否是预期的类型.如果是,那么此处就认为它是一个良构的异常,直接将该异常的消息传递给用户即可
- 第20行:`handlerError(1, err, msg)`.将日期和异常消息通过一个ID绑定在一起.我们可以使用自增ID或者GUID来确保这个ID是唯一的
- 第26行:`log.Printf("%#v\n", err)`.此处记录了异常的完整信息,以备需要深入了解具体发生了什么

运行结果:

```
go run main.go
12:00:51 lowLevel.LowLevelErr{
    error:customError.MyError{
        Inner:(*fs.PathError)(0xc000098180), 
        Message:"stat /bad/job/path: no such file or directory", 
        StackTrace:"
            goroutine 1 [running]:
            runtime/debug.Stack()
                /usr/local/go/src/runtime/debug/stack.go:24 +0x65
            code/chapter5/02-propagationError/customError.WrapError(
                {0x10d6ec8, 0xc000098180}, 
                {0xc0000b2030?, 0x10000000001?}, 
                {0x0?, 0x58?, 0x1711bb8?}
            )
                ConcurrencyInGo/code/chapter5/02-propagationError/customError/myError.go:19 +0x85
            code/chapter5/02-propagationError/lowLevel.IsGloballyExec(
                {0x10b7248?, 0x100b7be?}
            )
                ConcurrencyInGo/code/chapter5/02-propagationError/lowLevel/lowLevel.go:15 +0x6c
            code/chapter5/02-propagationError/intermediate.RunJob(
                {0x10b5caf, 0x1}
            )
                ConcurrencyInGo/code/chapter5/02-propagationError/intermediate/intermediate.go:15 +0x47
            main.main()
                ConcurrencyInGo/code/chapter5/02-propagationError/main.go:13 +0x56
        ", 
        Misc:map[string]interface {}{}
    }
}
[1] There was an unexpected issue; please report this as a bug.
```

我们可以看到,在这个异常的传播路径中的某处,该异常没有被正确处理,导致最终面向用户的代码无法确定异常中的消息是否人类可读(因为这个异常不是被调用模块自定义的类型),因此只能简单的打印一句`There was an unexpected issue; please report this as a bug.`来表明发生了意外情况.回顾`intermediate`模块可以发现问题:该模块没有封装来自`lowLevel`模块的异常.让我们纠正这个问题:

`ConcurrencyInGo/code/chapter5/02-propagationError/intermediate/intermediate.go`:

```go
package intermediate

import (
	"code/chapter5/02-propagationError/customError"
	"code/chapter5/02-propagationError/lowLevel"
	"os/exec"
)

type IntermediateErr struct {
	error
}

func RunJob(id string) error {
	const jobBinPath = "/bad/job/path"
	isExecutable, err := lowLevel.IsGloballyExec(jobBinPath)

	if err != nil {
		return IntermediateErr{customError.WrapError(err, "cannot run job %q: requisite binaries not available", id)}
	} else if isExecutable == false {
		return customError.WrapError(nil, "job binary is not executable") // 本包的错误
	}

	return exec.Command(jobBinPath, "--id="+id).Run()
}
```

- 第18行:`return IntermediateErr{customError.WrapError(err, "cannot run job %q: requisite binaries not available", id)}`.此处我们使用`intermediate`包自定义的异常来创建异常信息.这样我们可以隐藏关于二进制不运行的底层细节,因为我们认为这些细节信息对于`intermediate`的调用者而言不重要.

运行结果:

```
go run main.go
12:12:52 intermediate.IntermediateErr{
    error:customError.MyError{
        Inner:lowLevel.LowLevelErr{
            error:customError.MyError{
                Inner:(*fs.PathError)(0xc00010e030), 
                Message:"stat /bad/job/path: no such file or directory", 
                StackTrace:"
                    goroutine 1 [running]:
                    runtime/debug.Stack()
                        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
                    code/chapter5/02-propagationError/customError.WrapError(
                        {0x10d7118, 0xc00010e030}, 
                        {0xc000120000?, 0x0?}, 
                        {0x0?, 0x0?, 0x5?}
                    )
                        ConcurrencyInGo/code/chapter5/02-propagationError/customError/myError.go:19 +0x85
                    code/chapter5/02-propagationError/lowLevel.IsGloballyExec(
                        {0x10b7448?, 0x0?}
                    )
                        ConcurrencyInGo/code/chapter5/02-propagationError/lowLevel/lowLevel.go:15 +0x6c
                    code/chapter5/02-propagationError/intermediate.RunJob(
                        {0x10b5eaf, 0x1}
                    )
                        ConcurrencyInGo/code/chapter5/02-propagationError/intermediate/intermediate.go:15 +0x4a
                    main.main()
                        ConcurrencyInGo/code/chapter5/02-propagationError/main.go:13 +0x56
                ", 
                Misc:map[string]interface {}{}
            }
        }, 
        Message:"cannot run job \"1\": requisite binaries not available", 
        StackTrace:"
            goroutine 1 [running]:
            runtime/debug.Stack()
                /usr/local/go/src/runtime/debug/stack.go:24 +0x65
            code/chapter5/02-propagationError/customError.WrapError(
                {0x10d7258, 0xc0001080b0}, 
                {0x10bd559?, 0xc000046690?}, 
                {0xc0000ade70?, 0x113fbc8?, 0xc000046670?}
            )
                ConcurrencyInGo/code/chapter5/02-propagationError/customError/myError.go:19 +0x85
            code/chapter5/02-propagationError/intermediate.RunJob(
                {0x10b5eaf, 0x1}
            )
                ConcurrencyInGo/code/chapter5/02-propagationError/intermediate/intermediate.go:18 +0x1df
            main.main()
                ConcurrencyInGo/code/chapter5/02-propagationError/main.go:13 +0x56
        ", 
        Misc:map[string]interface {}{}
    }
}
[1] cannot run job "1": requisite binaries not available
```

可以看到,此时异常信息变的非常清晰:`requisite binaries not available`.

这种实现方法与标准库是兼容的,不过你也可以使用其他异常处理的包来实现这个思路.好消息是这种异常组织方式是比较自然的,你可以掩盖你顶层的错误处理并且详细的区分bug和良构的异常,并逐步确保你创建的所有异常都是良构的.